---
title: "GSVA_scoring"
author: "Wei"
date: "12/13/2021"
output: html_document
---
```{r}
library(limma)
library(GSVA)
```

# for SS2
```{r}
geneSets_EMP_SS2 <- list(Epi=list('ABCC3', 'ABHD11', 'ADGRG1', 'AGR2', 'AKR1B10', 'AP1M2', 'ARHGAP32', 'ARHGAP8', 'ATP2C2', 'AZGP1', 'BCAS1', 'BIK', 'BSPRY', 'C4orf19', 'CBLC', 'CD24', 'CD2AP', 'CDH1', 'CDS1', 'CEACAM1', 'CEACAM5', 'CEACAM6', 'CEACAM7', 'CKMT1A', 'CLDN3', 'CLDN4', 'CLDN7', 'CORO2A', 'CXADR', 'CYB561', 'DDR1', 'DHCR24', 'DSG2', 'DSP', 'EHF', 'ELF3', 'ELMO3', 'EPB41L4B', 'EPCAM', 'EPN3', 'EPS8L1', 'EPS8L2', 'ERBB2', 'ERBB3', 'ESRP1', 'ESRP2', 'EXPH5', 'EZR', 'F11R', 'FA2H', 'FAM174B', 'FGFR3', 'FUT2', 'FUT3', 'FXYD3', 'GALE', 'GALNT3', 'GALNT7', 'GDF15', 'GMDS', 'GPRC5A', 'GRHL2', 'HDHD3', 'IL20RA', 'INAVA', 'IRF6', 'JUP', 'KRT18', 'KRT19', 'KRT7', 'KRT8', 'LAD1', 'LLGL2', 'LRRC1', 'LSR', 'MANSC1', 'MAP7', 'MAPK13', 'MISP', 'MLPH', 'MPZL2', 'MST1R', 'MUC1', 'MYO5C', 'MYO6', 'NQO1', 'OCLN', 'OR7E14P', 'OVOL2', 'PERP', 'PHLDA2', 'PKP3', 'PLLP', 'PLPP2', 'PLS1', 'POF1B', 'PPL', 'PRR15L', 'PRSS8', 'PSCA', 'PTK6', 'PTPRF', 'RAB11FIP1', 'RAB25', 'RAPGEFL1', 'RBM47', 'RNF128', 'S100A14', 'S100P', 'SCNN1A', 'SDC4', 'SH3YL1', 'SLC16A5', 'SLC22A18', 'SLC35A3', 'SLC44A4', 'SORD', 'SPAG1', 'SPDEF', 'SPINT1', 'SPINT2', 'ST14', 'STAP2', 'STYK1', 'SYNGR2', 'TACSTD2', 'TFF1', 'TFF3', 'TJP2', 'TJP3', 'TMC5', 'TMEM30B', 'TMPRSS2', 'TMPRSS4', 'TOB1', 'TOM1L1', 'TOX3', 'TPD52', 'TRPM4', 'TSPAN1', 'TSPAN8', 'TTC39A', 'TUFT1', 'VAMP8', 'VAV3'),
                     
                 Mes=list('AKAP12', 'AKAP2', 'AKT3', 'ANGPTL2', 'ANK2', 'AP1S2', 'ASPN', 'AXL', 'BGN', 'BICC1', 'BNC2', 'C1R', 'C1S', 'C1orf54', 'CALD1', 'CAV1', 'CAVIN1', 'CCL2', 'CDH11', 'CDH2', 'CDK14', 'CEP170', 'CHN1', 'CHRDL1', 'CLEC2B', 'CLIC4', 'COL14A1', 'COL15A1', 'COL5A2', 'COL6A1', 'COL6A2', 'COLEC12', 'CRISPLD2', 'CRYAB', 'CSF2RB', 'CSRP2', 'CTSK', 'CXCL12', 'CXCL13', 'CXCR4', 'CYP1B1', 'DCN', 'DDR2', 'DPT', 'DPYSL3', 'DSE', 'ECM2', 'EFEMP1', 'EFEMP2', 'EMP3', 'ENPP2', 'EVI2A', 'FAP', 'FBLN1', 'FBN1', 'FERMT2', 'FGL2', 'FHL1', 'FLI1', 'FLRT2', 'FN1', 'FSTL1', 'FXYD6', 'FYN', 'GAS1', 'GEM', 'GFPT2', 'GLIPR1', 'GLYR1', 'GNG11', 'GPM6B', 'GREM1', 'GUCY1B1', 'HEG1', 'IFFO1', 'IGFBP5', 'IL10RA', 'ISLR', 'ITM2A', 'JAM2', 'JAM3', 'JCAD', 'KCNJ8', 'LHFPL6', 'LOX', 'LY96', 'MAF', 'MAFB', 'MAP1B', 'MEOX2', 'MFAP4', 'MMP2', 'MOXD1', 'MPDZ', 'MRC1', 'MYH10', 'MYL9', 'MYLK', 'NAP1L3', 'NR3C1', 'NUAK1', 'OLFML2B', 'OLFML3', 'PCOLCE', 'PDGFC', 'PDZRN3', 'PLEKHO1', 'PLN', 'PLXNC1', 'PMP22', 'PTGDS', 'PTGIS', 'PTPRC', 'PTX3', 'QKI', 'RARRES2', 'RECK', 'RGS2', 'RUNX1T1', 'SACS', 'SDC2', 'SEPT6', 'SERPINF1', 'SERPING1', 'SFRP1', 'SLC2A3', 'SLIT2', 'SNAI2', 'SOBP', 'SPARC', 'SPARCL1', 'SPOCK1', 'SRGN', 'SRPX', 'STON1', 'SYNE1', 'SYNE3', 'SYNM', 'SYT11', 'TAGLN', 'TCF4', 'TNC', 'TNS1', 'TPM2', 'TRPC1', 'TUBA1A', 'TUBB6', 'TWIST1', 'UCHL1', 'VCAM1', 'VCAN', 'VIM', 'WIPF1', 'WWTR1', 'ZCCHC24', 'ZEB1', 'ZEB2', 'ZFPM2'),
                 
                 combined=list('ABCC3', 'ABHD11', 'ADGRG1', 'AGR2', 'AKR1B10', 'AP1M2', 'ARHGAP32', 'ARHGAP8', 'ATP2C2', 'AZGP1', 'BCAS1', 'BIK', 'BSPRY', 'C4orf19', 'CBLC', 'CD24', 'CD2AP', 'CDH1', 'CDS1', 'CEACAM1', 'CEACAM5', 'CEACAM6', 'CEACAM7', 'CKMT1A', 'CLDN3', 'CLDN4', 'CLDN7', 'CORO2A', 'CXADR', 'CYB561', 'DDR1', 'DHCR24', 'DSG2', 'DSP', 'EHF', 'ELF3', 'ELMO3', 'EPB41L4B', 'EPCAM', 'EPN3', 'EPS8L1', 'EPS8L2', 'ERBB2', 'ERBB3', 'ESRP1', 'ESRP2', 'EXPH5', 'EZR', 'F11R', 'FA2H', 'FAM174B', 'FGFR3', 'FUT2', 'FUT3', 'FXYD3', 'GALE', 'GALNT3', 'GALNT7', 'GDF15', 'GMDS', 'GPRC5A', 'GRHL2', 'HDHD3', 'IL20RA', 'INAVA', 'IRF6', 'JUP', 'KRT18', 'KRT19', 'KRT7', 'KRT8', 'LAD1', 'LLGL2', 'LRRC1', 'LSR', 'MANSC1', 'MAP7', 'MAPK13', 'MISP', 'MLPH', 'MPZL2', 'MST1R', 'MUC1', 'MYO5C', 'MYO6', 'NQO1', 'OCLN', 'OR7E14P', 'OVOL2', 'PERP', 'PHLDA2', 'PKP3', 'PLLP', 'PLPP2', 'PLS1', 'POF1B', 'PPL', 'PRR15L', 'PRSS8', 'PSCA', 'PTK6', 'PTPRF', 'RAB11FIP1', 'RAB25', 'RAPGEFL1', 'RBM47', 'RNF128', 'S100A14', 'S100P', 'SCNN1A', 'SDC4', 'SH3YL1', 'SLC16A5', 'SLC22A18', 'SLC35A3', 'SLC44A4', 'SORD', 'SPAG1', 'SPDEF', 'SPINT1', 'SPINT2', 'ST14', 'STAP2', 'STYK1', 'SYNGR2', 'TACSTD2', 'TFF1', 'TFF3', 'TJP2', 'TJP3', 'TMC5', 'TMEM30B', 'TMPRSS2', 'TMPRSS4', 'TOB1', 'TOM1L1', 'TOX3', 'TPD52', 'TRPM4', 'TSPAN1', 'TSPAN8', 'TTC39A', 'TUFT1', 'VAMP8', 'VAV3','AKAP12', 'AKAP2', 'AKT3', 'ANGPTL2', 'ANK2', 'AP1S2', 'ASPN', 'AXL', 'BGN', 'BICC1', 'BNC2', 'C1R', 'C1S', 'C1orf54', 'CALD1', 'CAV1', 'CAVIN1', 'CCL2', 'CDH11', 'CDH2', 'CDK14', 'CEP170', 'CHN1', 'CHRDL1', 'CLEC2B', 'CLIC4', 'COL14A1', 'COL15A1', 'COL5A2', 'COL6A1', 'COL6A2', 'COLEC12', 'CRISPLD2', 'CRYAB', 'CSF2RB', 'CSRP2', 'CTSK', 'CXCL12', 'CXCL13', 'CXCR4', 'CYP1B1', 'DCN', 'DDR2', 'DPT', 'DPYSL3', 'DSE', 'ECM2', 'EFEMP1', 'EFEMP2', 'EMP3', 'ENPP2', 'EVI2A', 'FAP', 'FBLN1', 'FBN1', 'FERMT2', 'FGL2', 'FHL1', 'FLI1', 'FLRT2', 'FN1', 'FSTL1', 'FXYD6', 'FYN', 'GAS1', 'GEM', 'GFPT2', 'GLIPR1', 'GLYR1', 'GNG11', 'GPM6B', 'GREM1', 'GUCY1B1', 'HEG1', 'IFFO1', 'IGFBP5', 'IL10RA', 'ISLR', 'ITM2A', 'JAM2', 'JAM3', 'JCAD', 'KCNJ8', 'LHFPL6', 'LOX', 'LY96', 'MAF', 'MAFB', 'MAP1B', 'MEOX2', 'MFAP4', 'MMP2', 'MOXD1', 'MPDZ', 'MRC1', 'MYH10', 'MYL9', 'MYLK', 'NAP1L3', 'NR3C1', 'NUAK1', 'OLFML2B', 'OLFML3', 'PCOLCE', 'PDGFC', 'PDZRN3', 'PLEKHO1', 'PLN', 'PLXNC1', 'PMP22', 'PTGDS', 'PTGIS', 'PTPRC', 'PTX3', 'QKI', 'RARRES2', 'RECK', 'RGS2', 'RUNX1T1', 'SACS', 'SDC2', 'SEPT6', 'SERPINF1', 'SERPING1', 'SFRP1', 'SLC2A3', 'SLIT2', 'SNAI2', 'SOBP', 'SPARC', 'SPARCL1', 'SPOCK1', 'SRGN', 'SRPX', 'STON1', 'SYNE1', 'SYNE3', 'SYNM', 'SYT11', 'TAGLN', 'TCF4', 'TNC', 'TNS1', 'TPM2', 'TRPC1', 'TUBA1A', 'TUBB6', 'TWIST1', 'UCHL1', 'VCAM1', 'VCAN', 'VIM', 'WIPF1', 'WWTR1', 'ZCCHC24', 'ZEB1', 'ZEB2', 'ZFPM2'))

```

```{r}
gc_table_SS2 <- read.csv('ss2_gsva_gc.csv',row.names = 1)
gc_table_SS2 <- data.matrix(gc_table_SS2)
```

```{r}
gsva_out_SS2 <- gsva(gc_table_SS2, geneSets_EMP_SS2, mx.diff=TRUE, parallel.sz=30)
```

```{r}
write.csv(gsva_out_SS2, file='gsva_out_SS2.csv')
```

# For MULTI-seq
```{r}
geneSets_EMP_MULTI <- list(Epi=list('ABCC3', 'ABHD11', 'ADGRG1', 'AGR2', 'AP1M2', 'ARHGAP32', 'ARHGAP8', 'ATP2C2', 'AZGP1', 'BCAS1', 'BIK', 'BSPRY', 'C4orf19', 'CBLC', 'CD24', 'CD2AP', 'CDH1', 'CDS1', 'CEACAM1', 'CEACAM6', 'CKMT1A', 'CLDN3', 'CLDN4', 'CLDN7', 'CORO2A', 'CXADR', 'CYB561', 'DDR1', 'DHCR24', 'DSG2', 'DSP', 'EHF', 'ELF3', 'ELMO3', 'EPB41L4B', 'EPCAM', 'EPN3', 'EPS8L1', 'EPS8L2', 'ERBB2', 'ERBB3', 'ESRP1', 'ESRP2', 'EXPH5', 'EZR', 'F11R', 'FA2H', 'FAM174B', 'FGFR3', 'FUT2', 'FUT3', 'FXYD3', 'GALE', 'GALNT3', 'GALNT7', 'GDF15', 'GMDS', 'GPRC5A', 'GRHL2', 'HDHD3', 'IL20RA', 'INAVA', 'IRF6', 'JUP', 'KRT18', 'KRT19', 'KRT7', 'KRT8', 'LAD1', 'LLGL2', 'LRRC1', 'LSR', 'MANSC1', 'MAP7', 'MAPK13', 'MISP', 'MLPH', 'MPZL2', 'MST1R', 'MUC1', 'MYO5C', 'MYO6', 'NQO1', 'OCLN', 'OR7E14P', 'OVOL2', 'PERP', 'PHLDA2', 'PKP3', 'PLLP', 'PLPP2', 'PLS1', 'POF1B', 'PPL', 'PRR15L', 'PRSS8', 'PSCA', 'PTK6', 'PTPRF', 'RAB11FIP1', 'RAB25', 'RAPGEFL1', 'RBM47', 'RNF128', 'S100A14', 'S100P', 'SCNN1A', 'SDC4', 'SH3YL1', 'SLC16A5', 'SLC22A18', 'SLC35A3', 'SLC44A4', 'SORD', 'SPAG1', 'SPDEF', 'SPINT1', 'SPINT2', 'ST14', 'STAP2', 'STYK1', 'SYNGR2', 'TACSTD2', 'TFF1', 'TFF3', 'TJP2', 'TJP3', 'TMC5', 'TMEM30B', 'TMPRSS2', 'TMPRSS4', 'TOB1', 'TOM1L1', 'TOX3', 'TPD52', 'TRPM4', 'TSPAN1', 'TSPAN8', 'TTC39A', 'TUFT1', 'VAMP8', 'VAV3'),
                     
                 Mes=list('AKAP12', 'AKAP2', 'AKT3', 'ANK2', 'AP1S2', 'AXL', 'BGN', 'BICC1', 'BNC2', 'C1R', 'C1S', 'C1orf54', 'CALD1', 'CAV1', 'CAVIN1', 'CCL2', 'CDH11', 'CDH2', 'CDK14', 'CEP170', 'CHN1', 'CLEC2B', 'CLIC4', 'COL14A1', 'COL15A1', 'COL5A2', 'COL6A1', 'COL6A2', 'COLEC12', 'CRISPLD2', 'CRYAB', 'CSRP2', 'CTSK', 'CXCL12', 'CXCL13', 'CXCR4', 'CYP1B1', 'DDR2', 'DPT', 'DPYSL3', 'DSE', 'ECM2', 'EFEMP1', 'EFEMP2', 'EMP3', 'FAP', 'FBLN1', 'FBN1', 'FERMT2', 'FGL2', 'FHL1', 'FLI1', 'FLRT2', 'FN1', 'FSTL1', 'FXYD6', 'FYN', 'GAS1', 'GEM', 'GFPT2', 'GIMAP4', 'GLIPR1', 'GLYR1', 'GNG11', 'GPM6B', 'GREM1', 'GUCY1B1', 'HEG1', 'IFFO1', 'IGFBP5', 'ISLR', 'JAM2', 'JCAD', 'LHFPL6', 'LOX', 'LY96', 'MAF', 'MAFB', 'MAP1B', 'MEOX2', 'MFAP4', 'MMP2', 'MOXD1', 'MPDZ', 'MYH10', 'MYL9', 'MYLK', 'NAP1L3', 'NR3C1', 'NUAK1', 'OLFML3', 'PCOLCE', 'PDGFC', 'PDZRN3', 'PLEKHO1', 'PMP22', 'PTGDS', 'PTGIS', 'PTX3', 'QKI', 'RARRES2', 'RECK', 'RGS2', 'RUNX1T1', 'SACS', 'SDC2', 'SEPT6', 'SERPINF1', 'SERPING1', 'SFRP1', 'SLC2A3', 'SLIT2', 'SNAI2', 'SOBP', 'SPARC', 'SPARCL1', 'SPOCK1', 'SRGN', 'SRPX', 'STON1', 'SYNE1', 'SYNE3', 'SYNM', 'SYT11', 'TAGLN', 'TCF4', 'TNC', 'TNS1', 'TPM2', 'TRPC1', 'TUBA1A', 'TUBB6', 'TWIST1', 'UCHL1', 'VCAN', 'VIM', 'WIPF1', 'WWTR1', 'ZCCHC24', 'ZEB1', 'ZEB2', 'ZFPM2'),
                 
                 combined=list('ABCC3', 'ABHD11', 'ADGRG1', 'AGR2', 'AP1M2', 'ARHGAP32', 'ARHGAP8', 'ATP2C2', 'AZGP1', 'BCAS1', 'BIK', 'BSPRY', 'C4orf19', 'CBLC', 'CD24', 'CD2AP', 'CDH1', 'CDS1', 'CEACAM1', 'CEACAM6', 'CKMT1A', 'CLDN3', 'CLDN4', 'CLDN7', 'CORO2A', 'CXADR', 'CYB561', 'DDR1', 'DHCR24', 'DSG2', 'DSP', 'EHF', 'ELF3', 'ELMO3', 'EPB41L4B', 'EPCAM', 'EPN3', 'EPS8L1', 'EPS8L2', 'ERBB2', 'ERBB3', 'ESRP1', 'ESRP2', 'EXPH5', 'EZR', 'F11R', 'FA2H', 'FAM174B', 'FGFR3', 'FUT2', 'FUT3', 'FXYD3', 'GALE', 'GALNT3', 'GALNT7', 'GDF15', 'GMDS', 'GPRC5A', 'GRHL2', 'HDHD3', 'IL20RA', 'INAVA', 'IRF6', 'JUP', 'KRT18', 'KRT19', 'KRT7', 'KRT8', 'LAD1', 'LLGL2', 'LRRC1', 'LSR', 'MANSC1', 'MAP7', 'MAPK13', 'MISP', 'MLPH', 'MPZL2', 'MST1R', 'MUC1', 'MYO5C', 'MYO6', 'NQO1', 'OCLN', 'OR7E14P', 'OVOL2', 'PERP', 'PHLDA2', 'PKP3', 'PLLP', 'PLPP2', 'PLS1', 'POF1B', 'PPL', 'PRR15L', 'PRSS8', 'PSCA', 'PTK6', 'PTPRF', 'RAB11FIP1', 'RAB25', 'RAPGEFL1', 'RBM47', 'RNF128', 'S100A14', 'S100P', 'SCNN1A', 'SDC4', 'SH3YL1', 'SLC16A5', 'SLC22A18', 'SLC35A3', 'SLC44A4', 'SORD', 'SPAG1', 'SPDEF', 'SPINT1', 'SPINT2', 'ST14', 'STAP2', 'STYK1', 'SYNGR2', 'TACSTD2', 'TFF1', 'TFF3', 'TJP2', 'TJP3', 'TMC5', 'TMEM30B', 'TMPRSS2', 'TMPRSS4', 'TOB1', 'TOM1L1', 'TOX3', 'TPD52', 'TRPM4', 'TSPAN1', 'TSPAN8', 'TTC39A', 'TUFT1', 'VAMP8', 'VAV3','AKAP12', 'AKAP2', 'AKT3', 'ANK2', 'AP1S2', 'AXL', 'BGN', 'BICC1', 'BNC2', 'C1R', 'C1S', 'C1orf54', 'CALD1', 'CAV1', 'CAVIN1', 'CCL2', 'CDH11', 'CDH2', 'CDK14', 'CEP170', 'CHN1', 'CLEC2B', 'CLIC4', 'COL14A1', 'COL15A1', 'COL5A2', 'COL6A1', 'COL6A2', 'COLEC12', 'CRISPLD2', 'CRYAB', 'CSRP2', 'CTSK', 'CXCL12', 'CXCL13', 'CXCR4', 'CYP1B1', 'DDR2', 'DPT', 'DPYSL3', 'DSE', 'ECM2', 'EFEMP1', 'EFEMP2', 'EMP3', 'FAP', 'FBLN1', 'FBN1', 'FERMT2', 'FGL2', 'FHL1', 'FLI1', 'FLRT2', 'FN1', 'FSTL1', 'FXYD6', 'FYN', 'GAS1', 'GEM', 'GFPT2', 'GIMAP4', 'GLIPR1', 'GLYR1', 'GNG11', 'GPM6B', 'GREM1', 'GUCY1B1', 'HEG1', 'IFFO1', 'IGFBP5', 'ISLR', 'JAM2', 'JCAD', 'LHFPL6', 'LOX', 'LY96', 'MAF', 'MAFB', 'MAP1B', 'MEOX2', 'MFAP4', 'MMP2', 'MOXD1', 'MPDZ', 'MYH10', 'MYL9', 'MYLK', 'NAP1L3', 'NR3C1', 'NUAK1', 'OLFML3', 'PCOLCE', 'PDGFC', 'PDZRN3', 'PLEKHO1', 'PMP22', 'PTGDS', 'PTGIS', 'PTX3', 'QKI', 'RARRES2', 'RECK', 'RGS2', 'RUNX1T1', 'SACS', 'SDC2', 'SEPT6', 'SERPINF1', 'SERPING1', 'SFRP1', 'SLC2A3', 'SLIT2', 'SNAI2', 'SOBP', 'SPARC', 'SPARCL1', 'SPOCK1', 'SRGN', 'SRPX', 'STON1', 'SYNE1', 'SYNE3', 'SYNM', 'SYT11', 'TAGLN', 'TCF4', 'TNC', 'TNS1', 'TPM2', 'TRPC1', 'TUBA1A', 'TUBB6', 'TWIST1', 'UCHL1', 'VCAN', 'VIM', 'WIPF1', 'WWTR1', 'ZCCHC24', 'ZEB1', 'ZEB2', 'ZFPM2'))
```


```{r}
gc_table_MULTI <- read.csv('MULTI_gsva_gc.csv',row.names = 1)
gc_table_MULTI <- data.matrix(gc_table_MULTI)
```

```{r}
gsva_out_MULTI <- gsva(gc_table_MULTI, geneSets_EMP_MULTI, mx.diff=TRUE, parallel.sz=30)
```

```{r}
write.csv(gsva_out_MULTI, file='gsva_out_MULTI.csv')
```

